production:
  adapter: postgresql
  encoding: unicode
  database: nzitat_production
  host: localhost
  pool: 5
  username: 
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: nzitat_development
  host: localhost
  pool: 5
  username: 
  password: 

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: nzitat_test
  pool: 5
  host: localhost
  username: 
  password: